### ISSUE TITLE
Midterm feedback

### ISSUE THREAD

**Issue by philsinatra** [ellafromherz/IDM221-emf99#1]
## File names

You don't need to include the word 'page' in your file names.

```diff
- aboutpage.html
+ about.html
```

You also need to rename your index file:

```diff
- idex.html
+ index.html
```

## DRY (don't repeat yourself)

You have a lot of repetition in your code. For example:

```css
.AboutMe {
    font-family: 'DmSerifDisplay';
    font-weight: bolder;
    font-size: 10pt;
    text-align: center;
}

.Contact {
    font-family: 'DmSerifDisplay';
    font-weight: bolder;
    font-size: 10pt;
    text-align: center;
}
```

Name your classes based on the utility or function they serve. There's no need to have two classes with the same rules; simplify your code wherever possible.

## HTML structure

Think about the [HTML5 Elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) we've discussed and how you can improve the semantic structure of your code. For example, let's look at your [navigation](https://github.com/ellafromherz/IDM221-emf99/blob/8beab54df9133c95f43d0b7c1c991c7599c07c05/idex.html#L23-L42)

```html
<nav class="homepage">
        <h3>
            <a href="gallerypage.html"> gallery </a>
            <!--favorite photos-->
        </h3>
    </nav>
      
    <nav class="homepage">
        <h3>
            <a href="aboutpage.html"> about me </a>
            <!--lorem ipsm for now, get laney to write something-->
        </h3>
    </nav>
        
    <nav class="homepage">
        <h3>
            <a href="contactpage.html"> contact </a>
            <!--email, instagram, linkedin-->
        </h3>
    </nav>
```

Now think about the elements we discussed and how you could use them to solidify your structure. Your navigation is one list of links, but your code tells me you have three different navigation systems with headings that happen to be links. Simplify your structure.

```html
<nav>
  <ul>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
  </ul>
</nav>
```
